// Generates src/services/export/rasterizer/pdfjs-source.generated.ts from the
// installed pdfjs-dist (legacy build), so the image-export rasterizer can embed
// pdf.js in an offline WebView page. Runs on `npm install` / `npm ci`
// (postinstall). The output is not committed.
//
// The two pdf.js files are ES modules. The page loads them as inline
// <script type="module"> blocks, so:
// - the main build's final `export{...}` becomes `globalThis.pdfjsLib = {...}`;
// - the worker build already sets `globalThis.pdfjsWorker` (pdf.js then runs its
//   worker code on the main thread, with no separate worker file);
// - sequences that would end or alter an HTML script block are refused.

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
export const OUTPUT = join(root, 'src/services/export/rasterizer/pdfjs-source.generated.ts');

const UNSAFE_IN_SCRIPT = [/<\/script/i, /<!--/, /<script/i];

function assertInlineSafe(name, source) {
  for (const pattern of UNSAFE_IN_SCRIPT) {
    if (pattern.test(source)) throw new Error(`${name} contains ${pattern}, which cannot be inlined in a <script> block`);
  }
}

/**
 * Escapes non-ASCII characters as \uXXXX (per UTF-16 unit), which is equivalent JS in
 * strings, regular expressions, templates and comments. It keeps the embedded source
 * pure ASCII, so Hermes stores it at one byte per character instead of two.
 */
export function asciiOnly(source) {
  if (source.includes('String.raw')) throw new Error('String.raw would observe the escapes');
  return source.replace(/[\u0080-\uffff]/g, (c) => `\\u${c.charCodeAt(0).toString(16).padStart(4, '0')}`);
}

/** Replaces the module's final `export{a as B,C}` with a global object. */
export function exportsToGlobal(source, globalName) {
  const match = /export\{([^{}]*)\};?\s*$/.exec(source);
  if (!match) throw new Error('pdf.js main build: final export statement not found');
  const entries = match[1].split(',').map((entry) => {
    const parts = entry.trim().split(/\s+as\s+/);
    const local = parts[0];
    const exported = parts[1] ?? parts[0];
    if (!/^[\w$]+$/.test(local) || !/^[\w$]+$/.test(exported)) throw new Error(`unexpected export entry: ${entry}`);
    return `${exported}:${local}`;
  });
  return `${source.slice(0, match.index)}globalThis.${globalName}=Object.freeze({${entries.join(',')}});`;
}

export function buildPdfjsSource() {
  const require = createRequire(join(root, 'package.json'));
  const pkgPath = require.resolve('pdfjs-dist/package.json');
  const dir = dirname(pkgPath);
  const version = JSON.parse(readFileSync(pkgPath, 'utf8')).version;
  const main = readFileSync(join(dir, 'legacy/build/pdf.min.mjs'), 'utf8');
  const worker = readFileSync(join(dir, 'legacy/build/pdf.worker.min.mjs'), 'utf8');
  if (!worker.includes('globalThis.pdfjsWorker=')) throw new Error('pdf.js worker build no longer sets globalThis.pdfjsWorker');
  const mainGlobal = asciiOnly(exportsToGlobal(main, 'pdfjsLib'));
  assertInlineSafe('pdf.min.mjs', mainGlobal);
  const workerAscii = asciiOnly(worker);
  assertInlineSafe('pdf.worker.min.mjs', workerAscii);
  const hash = createHash('sha256').update(mainGlobal).update('\0').update(workerAscii).digest('hex');
  return [
    '// GENERATED by scripts/pdfjs-source.mjs on install. Do not edit or commit.',
    `// pdfjs-dist ${version} (legacy build), Apache-2.0.`,
    '/* eslint-disable */',
    `export const PDFJS_VERSION = ${JSON.stringify(version)};`,
    `export const PDFJS_SOURCE_SHA256 = ${JSON.stringify(hash)};`,
    `export const PDFJS_WORKER = ${JSON.stringify(workerAscii)};`,
    `export const PDFJS_MAIN = ${JSON.stringify(mainGlobal)};`,
    '',
  ].join('\n');
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  writeFileSync(OUTPUT, buildPdfjsSource());
  console.log(`pdf.js source written to ${OUTPUT.slice(root.length + 1)}`);
}
